FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine3.9 AS build
WORKDIR /app
 
COPY . ./dotnetapp/
WORKDIR /app/dotnetapp
RUN dotnet clean
#RUN dotnet restore *.sln
 
WORKDIR /app/
COPY . ./
WORKDIR /app/dotnetapp
RUN dotnet publish -c Release -o out
 
FROM build AS testrunner
WORKDIR /app/tests
COPY --from=build /app/dotnetapp/src/Daemon.Core.Test/*.* ./
RUN dotnet test --logger:trx
 
FROM mcr.microsoft.com/dotnet/core/runtime:2.2.4-alpine3.9 AS runtime
WORKDIR /app
COPY --from=build /app/dotnetapp/src/Daemon.Core/out ./
ENTRYPOINT ["dotnet", "Daemon.Core.dll"]